//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Answers__Questio__267ABA7A", "Questions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Questions), "Answers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Answers), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Student_A__Answe__33D4B598", "Answers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Answers), "Student_Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Student_Answer), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Exams__SubjectId__21B6055D", "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Subjects), "Exams", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Exams), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Marks__ExamId__2E1BDC42", "Exams", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Exams), "Marks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Marks), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__REQ__ExamId__29572725", "Exams", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Exams), "REQ", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.REQ), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Student_A__ExamI__32E0915F", "Exams", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Exams), "Student_Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Student_Answer), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__RSG__GroupId__1ED998B2", "Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Groups), "RSG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.RSG), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Marks__StudentId__2D27B809", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Users), "Marks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Marks), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Marks__SubjectId__2F10007B", "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Subjects), "Marks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Marks), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__REQ__QuestionId__2A4B4B5E", "Questions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Questions), "REQ", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.REQ), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Users__RoleId__1A14E395", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Roles), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Users), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__RSG__SubjectId__1DE57479", "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Subjects), "RSG", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.RSG), true)]
[assembly: EdmRelationshipAttribute("AcademyModel", "FK__Student_A__UserI__31EC6D26", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Academy.Users), "Student_Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Academy.Student_Answer), true)]

#endregion

namespace Academy
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AcademyEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AcademyEntities2 object using the connection string found in the 'AcademyEntities2' section of the application configuration file.
        /// </summary>
        public AcademyEntities2() : base("name=AcademyEntities2", "AcademyEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AcademyEntities2 object.
        /// </summary>
        public AcademyEntities2(string connectionString) : base(connectionString, "AcademyEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AcademyEntities2 object.
        /// </summary>
        public AcademyEntities2(EntityConnection connection) : base(connection, "AcademyEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answers> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answers>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answers> _Answers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Exams> Exams
        {
            get
            {
                if ((_Exams == null))
                {
                    _Exams = base.CreateObjectSet<Exams>("Exams");
                }
                return _Exams;
            }
        }
        private ObjectSet<Exams> _Exams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Groups> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Groups>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Groups> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Marks> Marks
        {
            get
            {
                if ((_Marks == null))
                {
                    _Marks = base.CreateObjectSet<Marks>("Marks");
                }
                return _Marks;
            }
        }
        private ObjectSet<Marks> _Marks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Questions> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Questions>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Questions> _Questions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<REQ> REQ
        {
            get
            {
                if ((_REQ == null))
                {
                    _REQ = base.CreateObjectSet<REQ>("REQ");
                }
                return _REQ;
            }
        }
        private ObjectSet<REQ> _REQ;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Roles> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Roles>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Roles> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RSG> RSG
        {
            get
            {
                if ((_RSG == null))
                {
                    _RSG = base.CreateObjectSet<RSG>("RSG");
                }
                return _RSG;
            }
        }
        private ObjectSet<RSG> _RSG;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student_Answer> Student_Answer
        {
            get
            {
                if ((_Student_Answer == null))
                {
                    _Student_Answer = base.CreateObjectSet<Student_Answer>("Student_Answer");
                }
                return _Student_Answer;
            }
        }
        private ObjectSet<Student_Answer> _Student_Answer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subjects> Subjects
        {
            get
            {
                if ((_Subjects == null))
                {
                    _Subjects = base.CreateObjectSet<Subjects>("Subjects");
                }
                return _Subjects;
            }
        }
        private ObjectSet<Subjects> _Subjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers(Answers answers)
        {
            base.AddObject("Answers", answers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Exams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExams(Exams exams)
        {
            base.AddObject("Exams", exams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Groups groups)
        {
            base.AddObject("Groups", groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Marks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarks(Marks marks)
        {
            base.AddObject("Marks", marks);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestions(Questions questions)
        {
            base.AddObject("Questions", questions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the REQ EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToREQ(REQ rEQ)
        {
            base.AddObject("REQ", rEQ);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Roles roles)
        {
            base.AddObject("Roles", roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RSG EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRSG(RSG rSG)
        {
            base.AddObject("RSG", rSG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Student_Answer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudent_Answer(Student_Answer student_Answer)
        {
            base.AddObject("Student_Answer", student_Answer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubjects(Subjects subjects)
        {
            base.AddObject("Subjects", subjects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Answers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answers object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="answerText">Initial value of the AnswerText property.</param>
        /// <param name="correct">Initial value of the Correct property.</param>
        public static Answers CreateAnswers(global::System.Int32 id, global::System.Int32 questionId, global::System.String answerText, global::System.Boolean correct)
        {
            Answers answers = new Answers();
            answers.Id = id;
            answers.QuestionId = questionId;
            answers.AnswerText = answerText;
            answers.Correct = correct;
            return answers;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AnswerText
        {
            get
            {
                return _AnswerText;
            }
            set
            {
                OnAnswerTextChanging(value);
                ReportPropertyChanging("AnswerText");
                _AnswerText = StructuralObject.SetValidValue(value, false, "AnswerText");
                ReportPropertyChanged("AnswerText");
                OnAnswerTextChanged();
            }
        }
        private global::System.String _AnswerText;
        partial void OnAnswerTextChanging(global::System.String value);
        partial void OnAnswerTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Correct
        {
            get
            {
                return _Correct;
            }
            set
            {
                OnCorrectChanging(value);
                ReportPropertyChanging("Correct");
                _Correct = StructuralObject.SetValidValue(value, "Correct");
                ReportPropertyChanged("Correct");
                OnCorrectChanged();
            }
        }
        private global::System.Boolean _Correct;
        partial void OnCorrectChanging(global::System.Boolean value);
        partial void OnCorrectChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Answers__Questio__267ABA7A", "Questions")]
        public Questions Questions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Questions>("AcademyModel.FK__Answers__Questio__267ABA7A", "Questions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Questions>("AcademyModel.FK__Answers__Questio__267ABA7A", "Questions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Questions> QuestionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Questions>("AcademyModel.FK__Answers__Questio__267ABA7A", "Questions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Questions>("AcademyModel.FK__Answers__Questio__267ABA7A", "Questions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Student_A__Answe__33D4B598", "Student_Answer")]
        public EntityCollection<Student_Answer> Student_Answer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student_Answer>("AcademyModel.FK__Student_A__Answe__33D4B598", "Student_Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student_Answer>("AcademyModel.FK__Student_A__Answe__33D4B598", "Student_Answer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Exams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Exams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Exams object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="subjectId">Initial value of the SubjectId property.</param>
        public static Exams CreateExams(global::System.Int32 id, global::System.String name, global::System.DateTime date, global::System.Int32 subjectId)
        {
            Exams exams = new Exams();
            exams.Id = id;
            exams.Name = name;
            exams.Date = date;
            exams.SubjectId = subjectId;
            return exams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubjectId
        {
            get
            {
                return _SubjectId;
            }
            set
            {
                OnSubjectIdChanging(value);
                ReportPropertyChanging("SubjectId");
                _SubjectId = StructuralObject.SetValidValue(value, "SubjectId");
                ReportPropertyChanged("SubjectId");
                OnSubjectIdChanged();
            }
        }
        private global::System.Int32 _SubjectId;
        partial void OnSubjectIdChanging(global::System.Int32 value);
        partial void OnSubjectIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Exams__SubjectId__21B6055D", "Subjects")]
        public Subjects Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__Exams__SubjectId__21B6055D", "Subjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__Exams__SubjectId__21B6055D", "Subjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Subjects> SubjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__Exams__SubjectId__21B6055D", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Subjects>("AcademyModel.FK__Exams__SubjectId__21B6055D", "Subjects", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Marks__ExamId__2E1BDC42", "Marks")]
        public EntityCollection<Marks> Marks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Marks>("AcademyModel.FK__Marks__ExamId__2E1BDC42", "Marks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Marks>("AcademyModel.FK__Marks__ExamId__2E1BDC42", "Marks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__REQ__ExamId__29572725", "REQ")]
        public EntityCollection<REQ> REQ
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REQ>("AcademyModel.FK__REQ__ExamId__29572725", "REQ");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REQ>("AcademyModel.FK__REQ__ExamId__29572725", "REQ", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Student_A__ExamI__32E0915F", "Student_Answer")]
        public EntityCollection<Student_Answer> Student_Answer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student_Answer>("AcademyModel.FK__Student_A__ExamI__32E0915F", "Student_Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student_Answer>("AcademyModel.FK__Student_A__ExamI__32E0915F", "Student_Answer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Groups object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Groups CreateGroups(global::System.Int32 id, global::System.String name)
        {
            Groups groups = new Groups();
            groups.Id = id;
            groups.Name = name;
            return groups;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__RSG__GroupId__1ED998B2", "RSG")]
        public EntityCollection<RSG> RSG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RSG>("AcademyModel.FK__RSG__GroupId__1ED998B2", "RSG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RSG>("AcademyModel.FK__RSG__GroupId__1ED998B2", "RSG", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Marks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marks : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Marks object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="examId">Initial value of the ExamId property.</param>
        /// <param name="subjectId">Initial value of the SubjectId property.</param>
        public static Marks CreateMarks(global::System.Int32 id, global::System.Int32 studentId, global::System.Int32 examId, global::System.Int32 subjectId)
        {
            Marks marks = new Marks();
            marks.Id = id;
            marks.StudentId = studentId;
            marks.ExamId = examId;
            marks.SubjectId = subjectId;
            return marks;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamId
        {
            get
            {
                return _ExamId;
            }
            set
            {
                OnExamIdChanging(value);
                ReportPropertyChanging("ExamId");
                _ExamId = StructuralObject.SetValidValue(value, "ExamId");
                ReportPropertyChanged("ExamId");
                OnExamIdChanged();
            }
        }
        private global::System.Int32 _ExamId;
        partial void OnExamIdChanging(global::System.Int32 value);
        partial void OnExamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubjectId
        {
            get
            {
                return _SubjectId;
            }
            set
            {
                OnSubjectIdChanging(value);
                ReportPropertyChanging("SubjectId");
                _SubjectId = StructuralObject.SetValidValue(value, "SubjectId");
                ReportPropertyChanged("SubjectId");
                OnSubjectIdChanged();
            }
        }
        private global::System.Int32 _SubjectId;
        partial void OnSubjectIdChanging(global::System.Int32 value);
        partial void OnSubjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Mark
        {
            get
            {
                return _Mark;
            }
            set
            {
                OnMarkChanging(value);
                ReportPropertyChanging("Mark");
                _Mark = StructuralObject.SetValidValue(value, "Mark");
                ReportPropertyChanged("Mark");
                OnMarkChanged();
            }
        }
        private Nullable<global::System.Int32> _Mark;
        partial void OnMarkChanging(Nullable<global::System.Int32> value);
        partial void OnMarkChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Marks__ExamId__2E1BDC42", "Exams")]
        public Exams Exams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__Marks__ExamId__2E1BDC42", "Exams").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__Marks__ExamId__2E1BDC42", "Exams").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Exams> ExamsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__Marks__ExamId__2E1BDC42", "Exams");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Exams>("AcademyModel.FK__Marks__ExamId__2E1BDC42", "Exams", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Marks__StudentId__2D27B809", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AcademyModel.FK__Marks__StudentId__2D27B809", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AcademyModel.FK__Marks__StudentId__2D27B809", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AcademyModel.FK__Marks__StudentId__2D27B809", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("AcademyModel.FK__Marks__StudentId__2D27B809", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Marks__SubjectId__2F10007B", "Subjects")]
        public Subjects Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__Marks__SubjectId__2F10007B", "Subjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__Marks__SubjectId__2F10007B", "Subjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Subjects> SubjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__Marks__SubjectId__2F10007B", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Subjects>("AcademyModel.FK__Marks__SubjectId__2F10007B", "Subjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Questions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Questions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Questions object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Questions CreateQuestions(global::System.Int32 id, global::System.String name)
        {
            Questions questions = new Questions();
            questions.Id = id;
            questions.Name = name;
            return questions;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Answers__Questio__267ABA7A", "Answers")]
        public EntityCollection<Answers> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answers>("AcademyModel.FK__Answers__Questio__267ABA7A", "Answers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answers>("AcademyModel.FK__Answers__Questio__267ABA7A", "Answers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__REQ__QuestionId__2A4B4B5E", "REQ")]
        public EntityCollection<REQ> REQ
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REQ>("AcademyModel.FK__REQ__QuestionId__2A4B4B5E", "REQ");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REQ>("AcademyModel.FK__REQ__QuestionId__2A4B4B5E", "REQ", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="REQ")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class REQ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new REQ object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="examId">Initial value of the ExamId property.</param>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static REQ CreateREQ(global::System.Int32 id, global::System.Int32 examId, global::System.Int32 questionId)
        {
            REQ rEQ = new REQ();
            rEQ.Id = id;
            rEQ.ExamId = examId;
            rEQ.QuestionId = questionId;
            return rEQ;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamId
        {
            get
            {
                return _ExamId;
            }
            set
            {
                OnExamIdChanging(value);
                ReportPropertyChanging("ExamId");
                _ExamId = StructuralObject.SetValidValue(value, "ExamId");
                ReportPropertyChanged("ExamId");
                OnExamIdChanged();
            }
        }
        private global::System.Int32 _ExamId;
        partial void OnExamIdChanging(global::System.Int32 value);
        partial void OnExamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__REQ__ExamId__29572725", "Exams")]
        public Exams Exams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__REQ__ExamId__29572725", "Exams").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__REQ__ExamId__29572725", "Exams").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Exams> ExamsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__REQ__ExamId__29572725", "Exams");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Exams>("AcademyModel.FK__REQ__ExamId__29572725", "Exams", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__REQ__QuestionId__2A4B4B5E", "Questions")]
        public Questions Questions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Questions>("AcademyModel.FK__REQ__QuestionId__2A4B4B5E", "Questions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Questions>("AcademyModel.FK__REQ__QuestionId__2A4B4B5E", "Questions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Questions> QuestionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Questions>("AcademyModel.FK__REQ__QuestionId__2A4B4B5E", "Questions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Questions>("AcademyModel.FK__REQ__QuestionId__2A4B4B5E", "Questions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Roles object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Roles CreateRoles(global::System.Int32 id, global::System.String name)
        {
            Roles roles = new Roles();
            roles.Id = id;
            roles.Name = name;
            return roles;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Users__RoleId__1A14E395", "Users")]
        public EntityCollection<Users> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users>("AcademyModel.FK__Users__RoleId__1A14E395", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users>("AcademyModel.FK__Users__RoleId__1A14E395", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="RSG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RSG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RSG object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="subjectId">Initial value of the SubjectId property.</param>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        public static RSG CreateRSG(global::System.Int32 id, global::System.Int32 subjectId, global::System.Int32 groupId)
        {
            RSG rSG = new RSG();
            rSG.Id = id;
            rSG.SubjectId = subjectId;
            rSG.GroupId = groupId;
            return rSG;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubjectId
        {
            get
            {
                return _SubjectId;
            }
            set
            {
                OnSubjectIdChanging(value);
                ReportPropertyChanging("SubjectId");
                _SubjectId = StructuralObject.SetValidValue(value, "SubjectId");
                ReportPropertyChanged("SubjectId");
                OnSubjectIdChanged();
            }
        }
        private global::System.Int32 _SubjectId;
        partial void OnSubjectIdChanging(global::System.Int32 value);
        partial void OnSubjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = StructuralObject.SetValidValue(value, "GroupId");
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private global::System.Int32 _GroupId;
        partial void OnGroupIdChanging(global::System.Int32 value);
        partial void OnGroupIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__RSG__GroupId__1ED998B2", "Groups")]
        public Groups Groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("AcademyModel.FK__RSG__GroupId__1ED998B2", "Groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("AcademyModel.FK__RSG__GroupId__1ED998B2", "Groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Groups> GroupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("AcademyModel.FK__RSG__GroupId__1ED998B2", "Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Groups>("AcademyModel.FK__RSG__GroupId__1ED998B2", "Groups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__RSG__SubjectId__1DE57479", "Subjects")]
        public Subjects Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__RSG__SubjectId__1DE57479", "Subjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__RSG__SubjectId__1DE57479", "Subjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Subjects> SubjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subjects>("AcademyModel.FK__RSG__SubjectId__1DE57479", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Subjects>("AcademyModel.FK__RSG__SubjectId__1DE57479", "Subjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Student_Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student_Answer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student_Answer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="examId">Initial value of the ExamId property.</param>
        /// <param name="answerId">Initial value of the AnswerId property.</param>
        public static Student_Answer CreateStudent_Answer(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 examId, global::System.Int32 answerId)
        {
            Student_Answer student_Answer = new Student_Answer();
            student_Answer.Id = id;
            student_Answer.UserId = userId;
            student_Answer.ExamId = examId;
            student_Answer.AnswerId = answerId;
            return student_Answer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamId
        {
            get
            {
                return _ExamId;
            }
            set
            {
                OnExamIdChanging(value);
                ReportPropertyChanging("ExamId");
                _ExamId = StructuralObject.SetValidValue(value, "ExamId");
                ReportPropertyChanged("ExamId");
                OnExamIdChanged();
            }
        }
        private global::System.Int32 _ExamId;
        partial void OnExamIdChanging(global::System.Int32 value);
        partial void OnExamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnswerId
        {
            get
            {
                return _AnswerId;
            }
            set
            {
                OnAnswerIdChanging(value);
                ReportPropertyChanging("AnswerId");
                _AnswerId = StructuralObject.SetValidValue(value, "AnswerId");
                ReportPropertyChanged("AnswerId");
                OnAnswerIdChanged();
            }
        }
        private global::System.Int32 _AnswerId;
        partial void OnAnswerIdChanging(global::System.Int32 value);
        partial void OnAnswerIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Student_A__Answe__33D4B598", "Answers")]
        public Answers Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answers>("AcademyModel.FK__Student_A__Answe__33D4B598", "Answers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answers>("AcademyModel.FK__Student_A__Answe__33D4B598", "Answers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Answers> AnswersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Answers>("AcademyModel.FK__Student_A__Answe__33D4B598", "Answers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Answers>("AcademyModel.FK__Student_A__Answe__33D4B598", "Answers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Student_A__ExamI__32E0915F", "Exams")]
        public Exams Exams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__Student_A__ExamI__32E0915F", "Exams").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__Student_A__ExamI__32E0915F", "Exams").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Exams> ExamsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Exams>("AcademyModel.FK__Student_A__ExamI__32E0915F", "Exams");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Exams>("AcademyModel.FK__Student_A__ExamI__32E0915F", "Exams", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Student_A__UserI__31EC6D26", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AcademyModel.FK__Student_A__UserI__31EC6D26", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AcademyModel.FK__Student_A__UserI__31EC6D26", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AcademyModel.FK__Student_A__UserI__31EC6D26", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("AcademyModel.FK__Student_A__UserI__31EC6D26", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Subjects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subjects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subjects object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Subjects CreateSubjects(global::System.Int32 id, global::System.String name)
        {
            Subjects subjects = new Subjects();
            subjects.Id = id;
            subjects.Name = name;
            return subjects;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Exams__SubjectId__21B6055D", "Exams")]
        public EntityCollection<Exams> Exams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Exams>("AcademyModel.FK__Exams__SubjectId__21B6055D", "Exams");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Exams>("AcademyModel.FK__Exams__SubjectId__21B6055D", "Exams", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Marks__SubjectId__2F10007B", "Marks")]
        public EntityCollection<Marks> Marks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Marks>("AcademyModel.FK__Marks__SubjectId__2F10007B", "Marks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Marks>("AcademyModel.FK__Marks__SubjectId__2F10007B", "Marks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__RSG__SubjectId__1DE57479", "RSG")]
        public EntityCollection<RSG> RSG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RSG>("AcademyModel.FK__RSG__SubjectId__1DE57479", "RSG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RSG>("AcademyModel.FK__RSG__SubjectId__1DE57479", "RSG", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AcademyModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="fName">Initial value of the FName property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Users CreateUsers(global::System.Int32 id, global::System.String login, global::System.String password, global::System.Int32 roleId, global::System.String fName, global::System.String phone, global::System.DateTime date)
        {
            Users users = new Users();
            users.Id = id;
            users.Login = login;
            users.Password = password;
            users.RoleId = roleId;
            users.FName = fName;
            users.Phone = phone;
            users.Date = date;
            return users;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false, "Login");
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value, "RoleId");
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LName
        {
            get
            {
                return _LName;
            }
            set
            {
                OnLNameChanging(value);
                ReportPropertyChanging("LName");
                _LName = StructuralObject.SetValidValue(value, true, "LName");
                ReportPropertyChanged("LName");
                OnLNameChanged();
            }
        }
        private global::System.String _LName;
        partial void OnLNameChanging(global::System.String value);
        partial void OnLNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FName
        {
            get
            {
                return _FName;
            }
            set
            {
                OnFNameChanging(value);
                ReportPropertyChanging("FName");
                _FName = StructuralObject.SetValidValue(value, false, "FName");
                ReportPropertyChanged("FName");
                OnFNameChanged();
            }
        }
        private global::System.String _FName;
        partial void OnFNameChanging(global::System.String value);
        partial void OnFNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Marks__StudentId__2D27B809", "Marks")]
        public EntityCollection<Marks> Marks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Marks>("AcademyModel.FK__Marks__StudentId__2D27B809", "Marks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Marks>("AcademyModel.FK__Marks__StudentId__2D27B809", "Marks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Users__RoleId__1A14E395", "Roles")]
        public Roles Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roles>("AcademyModel.FK__Users__RoleId__1A14E395", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roles>("AcademyModel.FK__Users__RoleId__1A14E395", "Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Roles> RolesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roles>("AcademyModel.FK__Users__RoleId__1A14E395", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Roles>("AcademyModel.FK__Users__RoleId__1A14E395", "Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AcademyModel", "FK__Student_A__UserI__31EC6D26", "Student_Answer")]
        public EntityCollection<Student_Answer> Student_Answer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student_Answer>("AcademyModel.FK__Student_A__UserI__31EC6D26", "Student_Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student_Answer>("AcademyModel.FK__Student_A__UserI__31EC6D26", "Student_Answer", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
